name: 🧪 Self-test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.1.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
        with:
          configurationFile: config-selftest.json
          token: ${{ secrets.RENOVATE_TOKEN }}
