name: 🧪 Self-test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@dd5302ec17783b2fc721b19ae7209b57b1587765 # v46.1.17
        with:
          configurationFile: config-selftest.json
          token: ${{ secrets.RENOVATE_TOKEN }}
