name: 🧪 Self-test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@3c68caaa9db5ff24332596591dc7c4fed8de16ce # v46.0.1
        with:
          configurationFile: config-selftest.json
          token: ${{ secrets.RENOVATE_TOKEN }}
