name: 🐶 Reviewdog

on:
  pull_request:
    branches:
      - main

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Spellcheck
        uses: reviewdog/action-misspell@v1.26.1
        with:
          reporter: github-pr-review
          fail_on_error: true

      - name: Action lint
        uses: reviewdog/action-actionlint@v1.62.0
        with:
          reporter: github-pr-review
          fail_on_error: true

      - name: YAML lint
        uses: reviewdog/action-yamllint@v1.20.0
        with:
          reporter: github-pr-review
          fail_on_error: true

      - name: Markdown lint
        uses: reviewdog/action-markdownlint@v0.26.0
        with:
          reporter: github-pr-review
          fail_on_error: true
