name: 🐶 Reviewdog

on:
  pull_request:
    branches:
      - main

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Spellcheck
        uses: reviewdog/action-misspell@v1.27.0
        with:
          reporter: github-pr-review
          fail_on_error: true

      - name: Action lint
        uses: reviewdog/action-actionlint@v1.68.0
        with:
          reporter: github-pr-review
          fail_on_error: true

      - name: YAML lint
        uses: reviewdog/action-yamllint@v1.21.0
        with:
          reporter: github-pr-review
          fail_on_error: true

      - name: Markdown lint
        uses: reviewdog/action-markdownlint@v0.26.2
        with:
          reporter: github-pr-review
          fail_on_error: true
